### PR TITLE
Add email signature page with generator and instructions

### PR DESCRIPTION
**Pull request by psherwinnicholls**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/DecodedCo/brand-guidelines/pull/48" target="_blank">ReviewNinja

**Comment by jonashaefele** [comment]
:star:

**Comment by psherwinnicholls** [comment]
:star:

**Comment by jonashaefele** [comment]
:ninja:

**Comment by psherwinnicholls** [comment]
:star2: :star: :star2:

**Comment by psherwinnicholls** [comment]
:star:

**Pull request merged**
