### PR TITLE
add basic html tempalte to css docs

### PR DESCRIPTION
**Pull request by jonashaefele**
for @amlwwalker

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/DecodedCo/brand-guidelines/pull/56" target="_blank">ReviewNinja

**Comment by amlwwalker** [comment]
@jonashaefele should we be concerned that serving static content (with this template) on S3 doesnt work as its over HTTP/HTTPS...?

:star

**Comment by amlwwalker** [comment]
:star:

**Comment by jonashaefele** [comment]
changed all the paths to HTTPS. @amlwwalker 

only merge this once the S3 bucket is on HTTPS.

**Pull request merged**
